### ISSUE TITLE
Error- "An unknown error occurred with ffmpeg"

### ISSUE THREAD

**Issue by Greenvillman** [DaGooseYT/FrameGUI#1]
The error
![the error photo](https://user-images.githubusercontent.com/89898431/131622479-d6c5e375-7d70-41f1-a5c0-521379b3a0b2.png)

ffmpeg logs
[ffmpeglogs.txt](https://github.com/DaGooseYT/FrameGUI/files/7088733/ffmpeglogs.txt)

aviscript
(sending as zip file cuz github doesnt support that file extension)
[aviscript.zip](https://github.com/DaGooseYT/FrameGUI/files/7088741/aviscript.zip)

The settings
![Screenshot 2021-09-01 114902](https://user-images.githubusercontent.com/89898431/131622701-629d8f79-1608-4e3e-8607-72c315496369.png)

![Screenshot 2021-09-01 114916](https://user-images.githubusercontent.com/89898431/131622703-cab3ed80-e34e-499c-b1b2-bcc48a1e2cbb.png)

![Screenshot 2021-09-01 114928](https://user-images.githubusercontent.com/89898431/131622704-a86f9c48-e082-4a48-870c-f341e1e385c5.png)

and the os is windows 10

can u help?

**Comment by DaGooseYT** [comment]
So the issue is that FFMpeg attempted to find an audio track to encode but your video doesn't have one, so that is why you got the error. Another user reported the same issue recently and I am working on a fix now (to ignore the audio encoding if the audio track doesn't exist). I'll keep you posted for when it's fixed.

**Comment by Greenvillman** [comment]
k

**Comment by Greenvillman** [comment]
thank u

**Comment by Greenvillman** [comment]
ok il close this issue
