### ISSUE TITLE
error - "An unknown error occurred with FFMpeg "

### ISSUE THREAD

**Issue by erosmike** [DaGooseYT/FrameGUI#4]
same issue @Greenvillman had

but works fine for some videos

![Screenshot (197)](https://user-images.githubusercontent.com/93816857/141246073-7a6fc404-7b66-4957-ae84-0a6013fa2b37.png)

ffmpeglogs text I Found by clicking the *"open logs path"*  is blank but I found it by clicking *"yes"* on the error message,
[ffmpeglogs.txt](https://github.com/DaGooseYT/FrameGUI/files/7518143/ffmpeglogs.txt)

aviscript
[aviscript.zip](https://github.com/DaGooseYT/FrameGUI/files/7518155/aviscript.zip)

the settings

![Screenshot (194)](https://user-images.githubusercontent.com/93816857/141247066-35cda973-c85e-4092-8349-523ebd8a2e7b.png)
I couldn't set the framerate in x264 settings

![Screenshot (195)](https://user-images.githubusercontent.com/93816857/141247072-ca1327a0-1112-4040-9175-b8f2a3cc48c3.png)
![Screenshot (196)](https://user-images.githubusercontent.com/93816857/141247078-e4d18b27-8aa3-4eab-8984-d0211c7148ca.png)

OS is Windows 10 

pls help

**Comment by DaGooseYT** [comment]
`C:\Users\Dulain\Desktop\ee\New folder\h3 60fps.mp4: Permission denied` 
It appears that you don't have the correct permissions to save the file to the path above. Try saving to another path and see if that works.

`"I couldn't set the framerate in x264 settings"`
That's because you have already defined the output framerate in the SVPFlow tab (60fps).

**Comment by erosmike** [comment]
never mind it was the antivirus, showed a message "ffmpeg.exe is trying to delete..." basically it said it was trying to delete the frames from the folder.
I disabled the antivirus and now it works.
but there seems to be a loss of quality tho...
