### ISSUE TITLE
NvENC Support?

### ISSUE THREAD

**Issue by Henriklmao** [DaGooseYT/FrameGUI#5]
Hey, 

first of all: Many thanks for that program, I'm planning to move from hybrid to this software, but the big giveaway is NVENC which is missing. I would love if you could somehow add an option for it.

Thank you

**Comment by DaGooseYT** [comment]
Hi,

I'm glad FrameGUI is working out for you for the most part. But since FrameGUI is approaching EOL, it will not receive anymore feature updates, only bug fixes. FrameGUI will be replaced by a more advanced video encoding tool (EncodeGUI) that will feature NVENC as an option for x264 and x265 codecs. The release is set for early next year. If you have anymore features that you would like added. please mention them in the anonymous FrameGUI survey: https://docs.google.com/forms/d/13eTGsTi7RbIXqdBOYs60VGjmSRUWNCSmcjCVPouj7oM

Thanks

**Comment by Henriklmao** [comment]
Beautiful, I look forward to it.
Will it be paid or free?

**Comment by DaGooseYT** [comment]
All of the encoding features (including NVENC) will be free (unlimited, too) in the free version of EncodeGUI. There will be a paid version to help with the web hosting fees for EncodeGUI's website and the paid version will add a dark theme UI, batch encoding, save encoding settings, automatic updates, and video tag editing. The paid version will cost $9.99 USD (one-time).
